events {
    worker_connections 1024;
}

http {
    upstream identity_cluster {
        server shteam-identity-1:3001; 
        server shteam-identity-2:3001;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://identity_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/catalog/ {
            proxy_pass http://shteam-catalog:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
