events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    upstream identity_cluster {
        server shteam-identity-1:3001;
        server shteam-identity-2:3001;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://identity_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/catalog/ {
            set $catalog_service http://shteam-catalog:3000;
            proxy_pass $catalog_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/orders/ {
            set $order_service http://shteam-order:3001;
            proxy_pass $order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/social/ {
            set $social_service http://shteam-social:3001;
            proxy_pass $social_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
